AllCops:
  TargetRubyVersion: 2.4
  NewCops: enable
  Layout/BeginEndAlignment:
    Enabled: true
  Layout/EmptyLinesAroundAttributeAccessor:
    Enabled: true

Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"
    - "fusuma-plugin-*.gemspec"

Metrics/LineLength:
  Max: 100
  Exclude:
    - "fusuma-plugin-*.gemspec"
